.github/workflows/container-image.yml, .gitignore, Dockerfile, makefile
Adds a container image, as well as a release workflow that checks out the code, builds, builds the container image and publishes it to the registry.
=> Containerimage

internal/business/persisted_operations/persisted_operations.go
Update reload metrics for peristed operations, include result label
=> fix(loader-metrics): Update reload metrics, include result

.golangci.yaml, cmd/main.go, cmd/main_test.go, internal/app/config/config.go, internal/business/aliases/aliases.go, internal/business/block_field_suggestions/block_field_suggestions.go, internal/business/block_field_suggestions/block_field_suggestions_test.go, internal/business/middleware/recover.go, internal/business/persisted_operations/dir_loader.go, internal/business/persisted_operations/gcp_storage_loader.go, internal/business/persisted_operations/loader.go, internal/business/persisted_operations/memory_loader.go, internal/business/persisted_operations/persisted_operations.go, internal/business/persisted_operations/persisted_operations_test.go, internal/business/proxy/proxy.go, internal/business/proxy/proxy_test.go, internal/business/readiness/readiness_test.go
Expand linting configuration, fix linting errors accordingly
=> Expand linting configuration

.github/dependabot.yml
Add basic dependabot configuration for auto-managing dependencies
=> feat(dependabot): Create dependabot.yml

.github/dependabot.yml
Update dependabot to group PRs
=> chore(dependabot): Group PRs

.gitignore, .idea/.gitignore, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml, go.mod
I could not setup my local development environment due to some conflicts with the .idea folder which is checked into git.
I have removed the .idea/ folder and added it to .gitignore.
Also ran `go mod tidy`
=> Improve gitignore and remove Jetbrains IDE files

internal/business/aliases/aliases.go, internal/business/max_depth/max_depth.go, internal/business/persisted_operations/persisted_operations.go, internal/business/tokens/tokens.go
Remove the histograms tracking latency on individual protections as the durations are too small to track
=> feat(metrics): Remove histograms since durations are too tiny to track

internal/http/proxy/proxy.go, internal/http/proxy/proxy_test.go
fix(xff): Properly forward x-forwarded-for on proxy
=> fix(xff): Properly forward x-forwarded-for on proxy

internal/business/gql/gql.go, internal/business/persisted_operations/persisted_operations.go, internal/business/persisted_operations/persisted_operations_test.go, internal/business/protect/protect.go
=> properly forward operation name for non persisted operations

docs/protections/access_logging.md, internal/app/config/config_test.go, internal/business/rules/accesslogging/accesslogging.go
Fix default config value for access logging
=> feat(access-logging): Fix default config

.github/CODEOWNERS, internal/business/persistedoperations/dir_loader.go, internal/business/persistedoperations/gcp_storage_loader.go, internal/business/persistedoperations/persisted_operations.go
Issue still observed, putting back workaround and creating more insights through logging.
Also refactoring to clean up the code
=> Fix persisted ops loading

.github/workflows/container-image.yml, .github/workflows/go.yml, .github/workflows/golangci-lint.yml, Dockerfile, README.md, docs/run/docker.md, docs/run/kubernetes.md, go.mod, internal/business/protect/protect.go, internal/business/rules/aliases/aliases.go, internal/business/rules/max_depth/max_depth.go, makefile
Update go version to 1.23
Update golangci-lint to 1.60.1
=> feat(go-1.23): Update version

README.md, cmd/main.go, docs/README.md, docs/configuration.md, docs/protections/block_field_suggestions.md, docs/protections/obfuscate_upstream_errors.md, docs/run/docker.md, docs/run/tracing.md
Several documentation improvements
=> Clean docs

cmd/main.go, cmd/main_test.go, cmd/validate.go, cmd/validate_test.go, internal/app/config/config.go, internal/app/config/config_test.go, internal/app/http/http.go, internal/app/log/log.go, internal/business/persistedoperations/persisted_operations.go, internal/business/rules/accesslogging/accesslogging.go, internal/business/rules/aliases/aliases.go, internal/business/rules/batch/batch.go, internal/business/rules/block_field_suggestions/block_field_suggestions.go, internal/business/rules/enforce_post/enforce_post.go, internal/business/rules/max_depth/max_depth.go, internal/business/rules/tokens/tokens.go, internal/business/schema/schema.go, internal/business/validation/model.go, internal/http/proxy/proxy.go
Many small improvements including
- rework of configuration setup
- better handling of default vs user override configuration
- improved tests
=> General improvements

README.md, cmd/main_test.go, docs/configuration.md, docs/protections/max_depth.md, go.mod, go.sum, internal/app/config/config_test.go, internal/business/protect/protect.go, internal/business/rules/max_depth/max_depth.go, internal/business/rules/max_depth/max_depth_test.go
Add max depth protection for nested list fields to prevent amplification attacks
=> Max list depth

docs/configuration.md
Clean up configuration documentation
=> docs(config): Cleanup

docs/protections/max_batch.md, internal/business/rules/batch/batch.go
Adds a size label to the batch protection rule to be able to see which batch sizes occur.
=> feat(batch): Add counter for batch size, fix metric

cmd/main.go, cmd/main_test.go, docs/run/kubernetes.md
Fixes command line argument parsing bug, wrote additional test cases
=> Fix command parsing

.github/workflows/release.yml
Fixes the build version being embedded in the binary
=> ci(build-version): Fix build version

docs/protections/max_tokens.md, internal/app/config/config_test.go, internal/business/protect/protect.go, internal/business/rules/tokens/tokens.go, internal/business/rules/tokens/tokens_test.go, internal/business/trusteddocuments/persisted_operations.go
This PR adds override capabilities to allow specific operations to have higher max-token limits than the specified general limit.
=> feat(tokens): Add override capabilities
